#!/usr/bin/env python3
"""Render task and roadmap views from the canonical ledger, without dependencies."""
from __future__ import annotations
import argparse
import json
from pathlib import Path


def expanded_task(plan: dict, task: dict) -> dict:
    return {**plan.get('legacyTaskMetadata', {}).get(task['id'], {}), **task}


def ordered_ids(ids: list[str], tasks: dict) -> list[str]:
    """Stable dependency order within a wave; external prerequisites retain wave order."""
    remaining=list(ids); result=[]
    while remaining:
        ready=[i for i in remaining if not set(tasks[i]['dependsOn']) & set(remaining)]
        if not ready:
            raise ValueError('dependency cycle in wave')
        for i in ready:
            remaining.remove(i); result.append(i)
    return result


def render(plan: dict) -> dict[str, str]:
    tasks={t['id']:expanded_task(plan,t) for t in plan['tasks']}
    native_ids=[i for w in plan['waves'] for i in ordered_ids(w['taskIds'],tasks)]
    successors=[t for t in plan['tasks'] if t['id'] not in plan['legacyTaskMetadata']]
    task_lines=['# Vital Rehearsal task contracts','',
        'Generated by `python3 tools/render_plan.py` from [plan/tasks.json](plan/tasks.json). Edit the canonical ledger and regenerate. [STATUS.md](STATUS.md) records narrative evidence and unresolved gates.','',
        f'{len(successors)} proposed successor outcomes plus 27 unchanged historical records. The {len(native_ids)} native-publication outcomes include the three foundations once; the original 24 aggregate contracts remain history, not duplicate deliverables. Planning rows do not prove implementation or scientific acceptance.','']
    delivery=plan.get('currentDelivery')
    if delivery:
        task_lines += ['Current delivery: '+delivery['dispatchId']+'. See [v1.0 contract](docs/v1/CONTRACT.md); original acceptances remain preserved.','']
    for task in tasks.values():
        task_lines += [f"## {task['id']} — {task['title']}",'',
          f"- Wave: {task['wave']}; status: **{task['status']}**; owner: assign in a bounded execution packet.",
          '- Dependencies: '+(', '.join(task['dependsOn']) or 'none')+'.',
          '- Textual-only prerequisites: '+('; '.join(task.get('textualPrerequisites',[])) or 'none recorded')+'.',
          '- Owned scope: '+', '.join('`'+p+'`' for p in task['ownedPaths'])+'.',
          '- Outcome: '+task['outcome'],
          '- Feature area: '+task['featureArea']+'.',
          '- Release horizon: '+task['targetRelease']+'.',
          '- Acceptance: '+task['acceptance'],
          '- Sources/decisions: '+', '.join(task['sourceRefs'])+'.',
          '- Risk/evidence needs: '+' '.join(task['riskEvidenceNeeds']),
          '- Evidence: '+('; '.join(task.get('evidence',[])) or 'not yet recorded')+'.','']
    road=['# Vital Rehearsal outcome roadmap','',
       'Generated from [plan/tasks.json](plan/tasks.json); [TASKS.md](TASKS.md) contains the complete contracts. [STATUS.md](STATUS.md) separates implementation, automated results, scientific evidence, human review and public release.','',
       plan['objective'],'',f"**{len(successors)} successor outcomes; {len(native_ids)} native-publication outcomes; {len(plan['waves'])} waves.** The original 27 records and nine original waves remain unchanged in [lineage](plan/lineage/foundation-2026-09-07/plan__tasks.json). Their 24 aggregate research outcomes are mapped to successors and not counted twice in the native plan.",'',
       'The preserved original path is admission and rights → immutable study → real admitted adapter → independent source-based evaluation → durable bundles and recovery → qualified review → authorized public release → external public-artifact reproduction → native plan readback. The current finite v1.0 contract is docs/v1/CONTRACT.md; bounded exact-exposure numerical admission now supplements the original software control. Wave entry dependencies are integration prerequisites; each task’s explicit prerequisites govern work that may proceed independently.','',
       'Wave order expresses integration and release horizon, not dates or promised throughput. Later and exploratory scope does not expand the finite current v1.0 contract. Public access: '+plan['accessInstructions']['text'],'',
       '## Limits','']+['- '+x for x in plan['limits']]+['']
    for wave in plan['waves']:
        road += [f"## Wave {wave['id']}: {wave['name']}",'',
          'Outcome: '+wave['outcome'],'','Release horizon: '+wave['targetRelease']+'.','',
          'Entry dependencies: '+(', '.join(wave['entryDependencies']) or 'accepted historical foundation')+'.','',
          'Exit evidence: every assigned acceptance below must be supported at its specified evidence level; unfulfilled human or scientific gates remain pending.','']
        for i in ordered_ids(wave['taskIds'],tasks):
            t=tasks[i]
            road += [f"- **{i}: {t['title']}.** {t['acceptance']} Status: **{t['status']}**."]
        road += ['']
    road += ['## Source treatment and prerequisite coverage','',
        'Each original acceptance, status, owned scope and structured edge is preserved. A narrow successor can complete without satisfying its broader source contract. Original textual-only prerequisites are separately recorded as none recorded, not inferred missing.','',
        '| Source | Treatment | Successors |','| --- | --- | --- |']
    for mapping in plan['sourceMappings']:
        road.append(f"| {mapping['sourceId']} | {mapping['treatment']} | {', '.join(mapping['successorIds'])} |")
    export={'schemaVersion':1,'project':plan['project'],'canonicalSource':'plan/tasks.json','objective':plan['objective'],'limits':plan['limits'],
      'counts':{'canonicalRecords':len(tasks),'originalHistoricalRecords':27,'successorOutcomes':len(successors),'nativeOutcomes':len(native_ids),'nativeWaves':len(plan['waves'])},
      'publication':plan['publication'],'accessInstructions':plan['accessInstructions'],'currentDelivery':plan.get('currentDelivery'),
      'nativeWorkflow':'Create authorized draft tasks, reconcile actual returned IDs, save a draft task plan, submit its exact revision, obtain actual approval/review, then read back public native pages. This file does not perform publication or claim native completion.',
      'waves':[{**w,'taskIds':ordered_ids(w['taskIds'],tasks)} for w in plan['waves']],
      'tasks':[tasks[i] for i in native_ids], 'sourceMappings':plan['sourceMappings'],
      'dependencies':[{'taskId':i,'dependsOnTaskIds':tasks[i]['dependsOn']} for i in native_ids],
      'platformIdMapping':[{'sourceKey':'vital-rehearsal:'+i,'platformId':tasks[i].get('platformId')} for i in native_ids]}
    return {'TASKS.md':'\n'.join(task_lines).rstrip()+'\n','ROADMAP.md':'\n'.join(road).rstrip()+'\n','plan/roadmap-export.json':json.dumps(export,indent=2,ensure_ascii=False)+'\n'}


def main() -> int:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root',type=Path,default=Path(__file__).resolve().parent.parent)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    plan=json.loads((args.root/'plan/tasks.json').read_text())
    stale=[]
    for name,content in render(plan).items():
        path=args.root/name
        if args.check:
            if not path.exists() or path.read_text()!=content: stale.append(name)
        else: path.write_text(content,encoding='utf-8')
    if stale:
        print('Stale generated views: '+', '.join(stale)); return 1
    print('Plan views '+('match canonical ledger.' if args.check else 'rendered.')); return 0

if __name__=='__main__':
    raise SystemExit(main())
